In [1]:
import numpy as np

# ques1 (a)
arr=np.array([1,2,3,6,4,5])
print("Original : ",arr)

print("Reversed (slicing):", arr[::-1])

Original :  [1 2 3 6 4 5]
Reversed (slicing): [5 4 6 3 2 1]


In [2]:
#ques 1(b)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Original:\n", array1)

print("Flattened (flatten):", array1.flatten())

Original:
 [[1 2 3]
 [2 4 5]
 [1 2 3]]
Flattened (flatten): [1 2 3 2 4 5 1 2 3]


In [3]:
# ques1 (c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print("Equal:", np.array_equal(arr1, arr2))   # True
print("Element-wise comparison:\n", arr1 == arr2)

Equal: True
Element-wise comparison:
 [[ True  True]
 [ True  True]]


In [7]:
# ques 1(d)
x = np.array([1,2,3,4,5,1,2,1,1,1])
val_x = np.bincount(x).argmax()
indices_x = np.where(x == val_x)
print("x -> Most frequent:", val_x, "Indices:", indices_x)


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
val_y = np.bincount(y).argmax()
indices_y = np.where(y == val_y)
print("y -> Most frequent:", val_y, "Indices:", indices_y)




x -> Most frequent: 1 Indices: (array([0, 5, 7, 8, 9]),)
y -> Most frequent: 1 Indices: (array([0, 1, 2]),)


In [8]:
#ques1(e)

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Matrix:\n", gfg)

print("Sum of all elements:", gfg.sum())
print("Row-wise sum:", gfg.sum(axis=1))
print("Column-wise sum:", gfg.sum(axis=0))

Matrix:
 [[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements: 45
Row-wise sum: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]


In [9]:
#ques1(f)

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

print("Sum of diagonal elements:", np.trace(n_array))

# Eigen values & vectors
eigen_values, eigen_vectors = np.linalg.eig(n_array)
print("Eigenvalues:", eigen_values)
print("Eigenvectors:\n", eigen_vectors)

# Inverse
print("Inverse:\n", np.linalg.inv(n_array))

# Determinant
print("Determinant:", np.linalg.det(n_array))

Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [10]:
#ques1(g)

# First case
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print("Multiplication (p1*q1):\n", np.dot(p1, q1))
print("Covariance:\n", np.cov(p1.flatten(), q1.flatten()))

# Second case
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

print("Multiplication (p2*q2):\n", np.dot(p2, q2))
print("Covariance:\n", np.cov(p2.flatten(), q2.flatten()))

Multiplication (p1*q1):
 [[16 19]
 [26 31]]
Covariance:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Multiplication (p2*q2):
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [11]:
#ques1(h)

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("Inner product:\n", np.inner(x, y))
print("Outer product:\n", np.outer(x, y))

# Cartesian product using meshgrid + reshape
cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print("Cartesian product:\n", cartesian)

Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [12]:
# ques 2(a)

array = np.array([[1, -2, 3], [-4, 5, -6]])
# i
print("Absolute values:\n", np.abs(array))

# ii
# Flattened array
print("Flattened percentiles:")
print("25th:", np.percentile(array, 25))
print("50th:", np.percentile(array, 50))
print("75th:", np.percentile(array, 75))

# Column-wise
print("\nColumn-wise percentiles:")
print("25th:", np.percentile(array, 25, axis=0))
print("50th:", np.percentile(array, 50, axis=0))
print("75th:", np.percentile(array, 75, axis=0))

# Row-wise
print("\nRow-wise percentiles:")
print("25th:", np.percentile(array, 25, axis=1))
print("50th:", np.percentile(array, 50, axis=1))
print("75th:", np.percentile(array, 75, axis=1))

# iii
# Flattened
print("\nFlattened:")
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Std Dev:", np.std(array))

# Column-wise
print("\nColumn-wise:")
print("Mean:", np.mean(array, axis=0))
print("Median:", np.median(array, axis=0))
print("Std Dev:", np.std(array, axis=0))

# Row-wise
print("\nRow-wise:")
print("Mean:", np.mean(array, axis=1))
print("Median:", np.median(array, axis=1))
print("Std Dev:", np.std(array, axis=1))


Absolute values:
 [[1 2 3]
 [4 5 6]]
Flattened percentiles:
25th: -3.5
50th: -0.5
75th: 2.5

Column-wise percentiles:
25th: [-2.75 -0.25 -3.75]
50th: [-1.5  1.5 -1.5]
75th: [-0.25  3.25  0.75]

Row-wise percentiles:
25th: [-0.5 -5. ]
50th: [ 1. -4.]
75th: [2.  0.5]

Flattened:
Mean: -0.5
Median: -0.5
Std Dev: 3.8622100754188224

Column-wise:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Std Dev: [2.5 3.5 4.5]

Row-wise:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Std Dev: [2.05480467 4.78423336]


In [13]:
# ques(2b)

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Truncated:", np.trunc(a))
print("Rounded:", np.round(a))

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [14]:
# ques(3)a

import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted array:", np.sort(array))
print("Indices of sorted array:", np.argsort(array))
print("4 smallest elements:", np.sort(array)[:4])
print("5 largest elements:", np.sort(array)[-5:])



Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [15]:
# ques(3)b

array2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers = array2[array2 == array2.astype(int)]
print("Integer elements only:", integers)
floats = array2[array2 != array2.astype(int)]
print("Float elements only:", floats)


Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [17]:
# ques (4)a
from PIL import Image
import numpy as np
import os

print("Current Working Directory:", os.getcwd())

def img_to_array(path, save_path="image_array.txt"):
   
    img = Image.open(path)
    arr = np.array(img)
    
    if arr.ndim == 2:
        print("Grayscale Image Detected")
        np.savetxt(save_path, arr, fmt='%d')
    elif arr.ndim == 3 and arr.shape[2] == 3:
        print("RGB Image Detected")
        np.savetxt(save_path, arr.reshape(-1, 3), fmt='%d')
    else:
        print("Unsupported image format")
        return None
    
    print(f"Image saved as array in: {save_path}")
    return arr

arr = img_to_array("sample.png", "image_array.txt")


Current Working Directory: C:\Users\Nishtha Goyal


FileNotFoundError: [Errno 2] No such file or directory: 'sample.png'

In [ ]:
# ques (4)b
def load_array(file_path):
    data = np.loadtxt(file_path, dtype=int)
    print("Loaded array shape:", data.shape)
    return data

# Function call
loaded_arr = load_array("image_array.txt")
print(loaded_arr)